version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    env_file:
      - ./backend/.env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306" 
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
