version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/cafedb
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cafedb
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306" 
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: