/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as EmployeeIndexImport } from './routes/employee/index'
import { Route as CafeIndexImport } from './routes/cafe/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EmployeeIndexRoute = EmployeeIndexImport.update({
  path: '/employee/',
  getParentRoute: () => rootRoute,
} as any)

const CafeIndexRoute = CafeIndexImport.update({
  path: '/cafe/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cafe/': {
      id: '/cafe/'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof CafeIndexImport
      parentRoute: typeof rootRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cafe': typeof CafeIndexRoute
  '/employee': typeof EmployeeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cafe': typeof CafeIndexRoute
  '/employee': typeof EmployeeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cafe/': typeof CafeIndexRoute
  '/employee/': typeof EmployeeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cafe' | '/employee'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cafe' | '/employee'
  id: '__root__' | '/' | '/cafe/' | '/employee/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CafeIndexRoute: typeof CafeIndexRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CafeIndexRoute: CafeIndexRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cafe/",
        "/employee/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cafe/": {
      "filePath": "cafe/index.tsx"
    },
    "/employee/": {
      "filePath": "employee/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
